FROM python:3.10-bullseye

ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

ENV USERNAME=dev
ENV HOMEDIR=/home/${USERNAME}

WORKDIR ${HOMEDIR}/app

# Install requirements and app
COPY ./app/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./app .

# Setup keys and certificates
WORKDIR ${HOMEDIR}
COPY ./setup-cert.sh ./setup-cert.sh
RUN ./setup-cert.sh

# Run application server
RUN export REQUESTS_CA_BUNDLE=$(realpath cert.pem)
WORKDIR ${HOMEDIR}/app
CMD ["flask", "--app" , "app", "run", "--cert=../cert.pem", "--key=../key.pem", "--host", "0.0.0.0", "--port", "7000"]
