#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --key KEYPATH --storage STORAGE --export FILENAME

Generate DID and export to file.

Arguments:
  --key KEYPATH         Private key to use
  --storage FOLDER      Folder containing key file
  --export FILENAME     File containing dumped key

Examples
  $ $(basename "$0") \
      --key /home/user/storage/key.json \
      --storage /home/user/storage \
      --export did.json
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

KEYPATH=
FILENAME=
STORAGE=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --key)
            KEYPATH="$2"
            shift
            shift
            ;;
        --storage)
            STORAGE="$2"
            shift
            shift
            ;;
        --export)
            FILENAME="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${KEYPATH} ]; then
    echo "[-] No key provided"
    usage && exit 1
fi

if [ -z ${STORAGE} ]; then
    echo "[-] No storage provided"
    usage && exit 1
fi


if [ -z ${FILENAME} ]; then
    echo "[-] No export file provided"
    usage && exit 1
fi

cd ${WALTDIR} && yes | ./waltid-cli.sh did create \
    --key=${KEYPATH} \
    --method=KEY \
    --did-doc-output="${STORAGE}/${FILENAME}"
    > /dev/null 2>&1

exit 0
