#!/bin/bash

usage_string="usage: 

$ $(basename "$0") [OPTIONS]

Get the last created DID. Exit with 2 if no created DID exists. See below for
more options.

Options:
  --list    List all created DIDs.
  --nr      Get the DID which appears at position nr of the list, 
            counting from one. Exit with 2 if the provided number 
            exceeds limits.
  --number  Number of created DIDs.

Examples
  $ $(basename "$0")
  $ $(basename "$0") --nr 7
  $ $(basename "$0") --list 
  $ $(basename "$0") --number 
"

usage() { echo -n "$usage_string" 1>&2; }

get_nr_dids() {
    NR_DIDS=$(./ssikit.sh did list | grep -c "\- [0-9]*:")
    echo $NR_DIDS
}

get_did() {
    POS=$1
    if [[ "$POS" -lt 1 ]] ; then
        echo "Index cannot be less than one: ${POS} < 1"
        exit 2
    fi
    NR_DIDS=$(get_nr_dids)
    if [[ "$POS" -gt "$NR_DIDS" ]]; then
        echo "Provided number exceeds limits: ${POS} > ${NR_DIDS}"
        exit 2
    fi
    DID=$(./ssikit.sh did list \
        | grep "\- ${POS}:" \
        | awk -F' ' '{print $3}' \
        | tr -d '"')
    echo $DID
}

get_last_did() {
    NR_DIDS=$(get_nr_dids)
    if [ ${NR_DIDS} == 0 ]; then
        echo "No created DIDs found" && exit 2
    fi
    POS=${NR_DIDS}
    echo $(get_did $POS)
}

get_did_list() {
    ./ssikit.sh did list
}


ACTION=DO_SHOW

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --list)
            ACTION=DO_LIST
            shift
            ;;
        --number)
            ACTION=DO_COUNT
            shift
            ;;
        --nr)
            POS="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

cd $WALTDIR

case $ACTION in
    DO_SHOW)
        if [ -z $POS ]; then
            get_last_did
        else
            get_did $POS
        fi
        shift
        ;;
    DO_LIST)
        get_did_list
        shift
        ;;
    DO_COUNT)
        get_nr_dids
        shift
        ;;
esac

exit 0
