#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --key KEYPATH --holder HOLDER_DID --issuer ISSUER_DID
--export FILEPATH

Issue VC and dump to file

Arguments:
  --key KEYPATH             Private key to use
  --holder HOLDER_DID       Holder DID
  --issuer ISSUER_DID       Issuer DID
  --storage FOLDER          Folder containing credential file
  --export FILEPATH         Filepath to export credential after issuance
"

usage() { echo -n "$usage_string" 1>&2; }

set -e


KEYPATH=
HOLDER_DID=
ISSUER_DID=
FILEPATH=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --key)
            KEYPATH="$2"
            shift
            shift
            ;;
        --holder)
            HOLDER_DID="$2"
            shift
            shift
            ;;
        --issuer)
            ISSUER_DID="$2"
            shift
            shift
            ;;
        --export)
            FILEPATH="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${KEYPATH} ]; then
    echo "[-] No key provided"
    usage && exit 1
fi

if [ -z ${HOLDER_DID} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ -z ${ISSUER_DID} ]; then
    echo "[-] No issuer DID provided"
    usage && exit 1
fi

if [ -z ${STORAGE} ]; then
    echo "[-] No storage provided"
    usage && exit 1
fi

if [ -z ${FILEPATH} ]; then
    echo "[-] No export file provided"
    usage && exit 1
fi

cd $WALTDIR

waltid-cli vc sign \
    --key=${KEYPATH} \
    --issuer=${ISSUER_DID} \
    --subject=${HOLDER_DID} \
    --overwrite \
    ${FILEPATH}

exit 0
