#!/bin/bash

usage_string="usage:

$ $(basename "$0") --holder DID --issuer DID --export FILE [OPTIONS]

Issue verifiable diploma and dump to file.

Purpose of this script is to issue verifiable diplomas in a non-interactive and 
unattended fashion. Order of arguments matters but is not validated. Take care 
to provide arguments in the correct order, otherwise the credential will be 
non-sensical or wrong or not issued.

NOTE: If you want to interactively generate a verifiable diploma, run directly the
issue-credential command.

Named arguments:
  --holder DID      DID of VC holder
  --issuer DID      DID of VC issuer
  --export OUTFILE  File to export credential after issuance

Order of rest arguments:
    person_identifier
    person_family_name
    person_given_name
    person_date_of_birth
    awarding_opportunity_id
    awarding_opportunity_identifier
    awarding_opportunity_location
    awarding_opportunity_started_at
    awarding_opportunity_ended_at
    awarding_body_preferred_name
    awarding_body_homepage
    awarding_body_registraction
    awarding_body_eidas_legal_identifier
    grading_scheme_id
    grading_scheme_title
    grading_scheme_description
    learning_achievement_id
    learning_achievement_title
    learning_achievement_description
    learning_achievement_additional_note
    learning_specification_id
    learning_specification_ects_credit_points
    learning_specification_eqf_level
    learning_specification_iscedf_code
    learning_specification_nqf_level
    learning_specification_evidence_id
    learning_specification_evidence_type
    learning_specification_verifier
    learning_specification_evidence_document
    learning_specification_subject_presence
    learning_specification_document_presence\n
"

usage() { echo -ne "$usage_string" 1>&2; }

set -e

HOLDER=
ISSUER=
OUTFILE=
args=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --holder)
            HOLDER="$2"
            shift
            shift
            ;;
        --issuer)
            ISSUER="$2"
            shift
            shift
            ;;
        --export)
            OUTFILE="$2"
            shift
            shift
            ;;
        *)
            args+="$1\n"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
    esac
done

if [ -z ${HOLDER} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ -z ${ISSUER} ]; then
    echo "[-] No issuer DID provided"
    usage && exit 1
fi

if [ -z ${OUTFILE} ]; then
    echo "[-] No export file provided"
    usage && exit 1
fi

printf $args | issue-credential \
    --template VerifiableDiploma \
    --proof-type LD_PROOF \
    --holder ${HOLDER} \
    --issuer ${ISSUER} \
    --export ${OUTFILE}

exit 0
