#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --holder DID --issuer DID --export OUTFILE [OPTIONS]

Issue VC and dump to file.

Arguments:
  --holder DID      DID of credential holder
  --issuer DID      DID of credential issuer
  --export OUTFILE  File to export credential after issuance

Options:
  --template        VC template to use. Default: VerifiableDiploma
  --proof-type      Proof type to be used for issuance. Default: LD_PROOF
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

TEMPLATE=VerifiableDiploma
PROOF_TYPE=LD_PROOF

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --holder)
            HOLDER="$2"
            shift
            shift
            ;;
        --issuer)
            ISSUER="$2"
            shift
            shift
            ;;
        --export)
            OUTFILE="$2"
            shift
            shift
            ;;
        --template)
            TEMPLATE="$2"
            shift
            shift
            ;;
        --proof-type)
            HOLDER="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${HOLDER} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ -z ${ISSUER} ]; then
    echo "[-] No issuer DID provided"
    usage && exit 1
fi

if [ -z ${OUTFILE} ]; then
    echo "[-] No export file provided"
    usage && exit 1
fi

cd $WALTDIR

./ssikit.sh vc issue \
    --template ${TEMPLATE} \
    --subject-did ${HOLDER} \
    --issuer-did ${ISSUER} \
    --proof-type ${PROOF_TYPE} \
    --proof-purpose assertion \
    --interactive \
    ${OUTFILE}

exit 0

