#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --file FILE

Load key to memory

Arguments:
  --file FILE       File containing the key in JWK format
"

usage() { echo -n "$usage_string" 1>&2; }

JWKFILE=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --file)
            JWKFILE="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${JWKFILE} ]; then
    echo '[-] No JWK file provided'
    usage 
    exit 1
fi

cd $WALTDIR

./ssikit.sh key import ${JWKFILE} >/dev/null 2>&1

exit 0
