#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --holder DID -c VC [-c VC ... ]

Create a verifiable presentation from provided credentials

Arguments:
  --holder DID            DID of the holder owning the provided credentials.
                          Must coincide with the credentialSubject.id attribute of
                          of the provided credentials.
  -c, --credential FILE   File containing verifiable credential. Can be given
                          multiple times.
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

HOLDER=
CREDENTIALS=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --holder)
            HOLDER="$2"
            shift
            shift
            ;;
        -c|--credential)
            CREDENTIALS+=" $2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${HOLDER} ]; then
    echo "[-] No holder DID provided"
    usage && exit 1
fi

if [ ${#CREDENTIALS[@]} -eq 0 ]; then
    echo "[-] No credentials provided"
    usage && exit 1
fi
    
cd $WALTDIR

resp=$(
    ./ssikit.sh vc present \
        --holder-did ${HOLDER} \
        ${CREDENTIALS}
)

echo $resp

exit 0
