#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --did DID --token FILE [OPTIONS]

DID onboarding and registration to EBSI.

NOTE: Tokens are taken from https://app.preprod.ebsi.eu/users-onboarding
and expire after 15 minutes.

Arguments:
  --did ALIAS     DID to onboard
  --token FILE    File containing the bearer token. Exit with 2 if expired
                  or malformed.

Options:
  --resolve       Resolve registered DID to check if it was anchored.

Examples
  $ $(basename "$0") --token bearer-token.txt --did zjmoeYH3t3FQn93qTqLUQ9j 
"

usage() { echo -ne "$usage_string" 1>&2; }

set -e

EBSI_PRFX="did:ebsi"
DO_RESOLVE=false
TOKEN=
DID=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        --token)
            TOKEN="$2"
            shift
            shift
            ;;
        -d|--did)
            if [[ "$2" =~ "$EBSI_PRFX".* ]]; then
                DID="$2"
            else
                DID="$EBSI_PRFX:$2"       # Prepend did:ebsi:
            fi
            shift
            shift
            ;;
        --resolve)
            DO_RESOLVE=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${DID} ]; then
    echo '[-] No DID provided'
    usage && exit 1
fi

if [ -z ${TOKEN} ]; then
    echo '[-] No token file provided'
    usage && exit 1
fi

cd ${WALTDIR}

resp=$(./ssikit.sh essif onboard --did ${DID} ${TOKEN})

if echo $resp | grep -q "invalid_jwt: JWT has expired"; then
    echo "EBSI onboarding failed: Token has expired"
    exit 2
fi

if echo $resp | grep -q "invalid_argument: Incorrect format JWT"; then
    echo "EBSI onboarding failed: Invalid token format"
    exit 2
fi

./ssikit.sh essif auth-api --did ${DID}
# TODO: Check response for error

./ssikit.sh essif did register --did ${DID}
# TODO: Check response for error

# if [ ${DO_RESOLVE} == true ]; then
#     resolve-did --did ${DID}  >/dev/null  # exit with 1 if not resolved
# fi
