#!/bin/bash

usage_string="usage: 

$ $(basename "$0") --presentation FILE [OPTIONS]

Verify credentials and return result

Arguments:
  -vp,--presentation FILE   Presentation (set of credentials) to verify

Options:
  TODO: Specify policies? All four policies are checked for the moment.

Examples
  $ $(basename "$0") ...
"

usage() { echo -n "$usage_string" 1>&2; }

set -e

PRESENTATION=

while [[ $# -gt 0 ]]
do
    arg="$1"
    case $arg in
        -vp|--presentation)
            PRESENTATION="$2"
            shift
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[-] Unknown option: ${arg}"
            usage
            exit 1
    esac
done

if [ -z ${PRESENTATION} ]; then
    echo '[-] No presentation provided'
    usage && exit 1
fi

cd $WALTDIR

resp=$(
  ./ssikit.sh vc verify \
      --policy JsonSchemaPolicy \
      --policy TrustedSubjectDidPolicy \
      --policy TrustedIssuerDidPolicy \
      --policy SignaturePolicy \
      ${PRESENTATION}
)

echo $resp
exit 0

